# Generated by Django 5.2.7 on 2025-10-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('page_source', models.CharField(blank=True, help_text="Readable page or section name where the form was submitted (e.g. 'SEO Automation').", max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, help_text='Full URL of the page where the form was submitted.', null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_interested', models.ForeignKey(blank=True, help_text='Selected service if submitted from homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='services.service')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
