# Generated by Django 5.2.5 on 2025-10-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
