# Generated by Django 5.2.5 on 2025-10-13 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_mainservice_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('show_on_home', models.BooleanField(default=False, help_text='Show this testimonial on the Home Page')),
                ('is_active', models.BooleanField(default=True)),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_service', models.ForeignKey(blank=True, help_text='Attach to a specific Main Service (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='services.mainservice')),
                ('sub_service', models.ForeignKey(blank=True, help_text='Attach to a specific Sub Service (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='services.subservice')),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
    ]
