# Generated by Django 5.2.7 on 2025-10-17 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_h1', models.CharField(blank=True, help_text='Main H1 for hero area', max_length=200)),
                ('hero_tagline', models.CharField(blank=True, help_text='Short tagline under the H1', max_length=300)),
                ('hero_background_image', models.ImageField(blank=True, help_text='Optional hero background/illustration', null=True, upload_to='service_hero_images/')),
                ('short_section_title', models.CharField(blank=True, max_length=200)),
                ('short_section_image', models.ImageField(blank=True, help_text='Image shown beside the short details (like illustration/card)', null=True, upload_to='service_short_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Details',
                'verbose_name_plural': 'Service Details',
            },
        ),
        migrations.CreateModel(
            name='BulletPointServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order for display (lower first)')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(0)])),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='services.servicedetails')),
            ],
            options={
                'verbose_name': 'Bullet Point',
                'verbose_name_plural': 'Bullet Points',
                'ordering': ['order'],
            },
        ),
    ]
