# Generated by Django 5.2.7 on 2025-10-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicedetails_bulletpointservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='hero_background_image',
        ),
    ]
