# Generated by Django 5.2.7 on 2025-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicedetails_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set to True to make this service Details visible on the site.'),
        ),
    ]
