# Generated by Django 5.2.7 on 2025-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='hero_h1',
            field=models.CharField(blank=True, help_text='Main H1 for hero area Separate with / for highlighting', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='hero_tagline',
            field=models.TextField(blank=True, help_text='Short tagline under the H1'),
        ),
    ]
