# Generated by Django 5.2.7 on 2025-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicedetails_hero_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='short_section_details',
            field=models.TextField(blank=True, help_text='Detailed description shown beside the bullet points.'),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='short_section_title',
            field=models.CharField(blank=True, help_text='Main H2 for hero area Separate with / for highlighting', max_length=200),
        ),
    ]
