# Generated by Django 5.2.7 on 2025-10-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicedetails_short_section_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_title', models.CharField(blank=True, help_text='Optional short label used inside the colored card.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-solid fa-cog', help_text="FontAwesome icon class (e.g., 'fa-solid fa-chart-line').", max_length=100)),
                ('color_theme', models.CharField(choices=[('accent', 'Accent / Blue'), ('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('red', 'Red')], default='accent', help_text='Controls the color background of the sub-service section.', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Optional image or illustration for this sub-service.', null=True, upload_to='sub_service_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of appearance in the section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_service', models.ForeignKey(help_text='Main service this sub-service belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.service')),
            ],
            options={
                'verbose_name': 'Sub Service',
                'verbose_name_plural': 'Sub Services',
                'ordering': ['parent_service', 'order'],
            },
        ),
    ]
