# Generated by Django 5.2.7 on 2025-10-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_subservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.subservice')),
            ],
            options={
                'verbose_name': 'Sub Service Feature',
                'verbose_name_plural': 'Sub Service Features',
                'ordering': ['order'],
            },
        ),
    ]
