# Generated by Django 5.2.7 on 2025-10-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_subservicefeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='short_title',
        ),
    ]
