# Generated by Django 5.2.7 on 2025-10-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_subservice_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='image',
        ),
    ]
