# Generated by Django 5.2.7 on 2025-10-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_subservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, help_text='Attach this FAQ to a main service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
                ('sub_service', models.ForeignKey(blank=True, help_text='Attach this FAQ to a sub-service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.subservice')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
